"use client";

import { useDeferredValue, useMemo, useState } from "react";
import { CalendarDays, List, Search, X } from "lucide-react";
import { communities, events, projects, students } from "@/lib/data/mock";
import { useDemoState } from "@/lib/demo/demo-store";
import { CommunityCard } from "@/components/catalog/community-card";
import { EventRow } from "@/components/catalog/event-row";
import { ProjectRow } from "@/components/catalog/project-row";
import { StudentCard } from "@/components/people/student-card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { CampusEvent, Community, Project, Student } from "@/types";

type DirectoryType="people"|"communities"|"projects"|"events";
const placeholders:Record<DirectoryType,string>={people:"Search name, username, skill or interest",communities:"Search communities or categories",projects:"Search projects, technologies or open roles",events:"Search events, locations or organizers"};
const searchable=(item:unknown)=>Object.values(item as Record<string,unknown>).flatMap(value=>Array.isArray(value)?value:[value]).join(" ").toLowerCase();

export function SearchableDirectory({type}:{type:DirectoryType}){
  const {state}=useDemoState();const [query,setQuery]=useState("");const [primary,setPrimary]=useState("All");const [secondary,setSecondary]=useState("All");const [interest,setInterest]=useState("All");const [collaboration,setCollaboration]=useState("All");const [view,setView]=useState<"list"|"calendar">("list");const deferred=useDeferredValue(query.trim().toLowerCase());
  const source=useMemo(()=>(type==="people"?students:type==="communities"?[...state.createdCommunities,...communities]:type==="projects"?[...state.createdProjects,...projects]:[...state.createdEvents,...events]),[state.createdCommunities,state.createdEvents,state.createdProjects,type]);
  const options=type==="people"?[...new Set(students.map(x=>x.program))]:type==="communities"?[...new Set((source as Community[]).map(x=>x.category))]:type==="projects"?[...new Set((source as Project[]).map(x=>x.status))]:[...new Set((source as CampusEvent[]).map(x=>x.category))];
  const secondaryOptions=type==="people"?[...new Set(students.flatMap(x=>x.skills))]:type==="projects"?[...new Set((source as Project[]).flatMap(x=>x.lookingFor))]:[];
  const filtered=source.filter(item=>{if(deferred&&!searchable(item).includes(deferred))return false;if(primary!=="All"){if(type==="people"&&(item as Student).program!==primary)return false;if(type==="communities"&&(item as Community).category!==primary)return false;if(type==="projects"&&(item as Project).status!==primary)return false;if(type==="events"&&(item as CampusEvent).category!==primary)return false;}if(secondary!=="All"){if(type==="people"&&!(item as Student).skills.includes(secondary))return false;if(type==="projects"&&!(item as Project).lookingFor.includes(secondary))return false;}if(type==="people"&&interest!=="All"&&!(item as Student).interests.includes(interest))return false;if(type==="people"&&collaboration!=="All"&&((item as Student).collaboration??((item as Student).available?"Open to projects":"Focused"))!==collaboration)return false;return true;});
  return <><div className="mb-7 flex flex-col gap-3 border-y py-4 lg:flex-row lg:items-center"><div className="relative max-w-xl flex-1"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="ps-9 pe-9 shadow-none" placeholder={placeholders[type]} aria-label={placeholders[type]}/>{query&&<button onClick={()=>setQuery("")} className="absolute end-2 top-1/2 -translate-y-1/2 rounded p-1 text-muted-foreground hover:text-foreground" aria-label="Clear search"><X className="size-3.5"/></button>}</div><select value={primary} onChange={e=>setPrimary(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm" aria-label={type==="people"?"Filter by program":"Filter by category"}><option>All</option>{options.map(x=><option key={x}>{x}</option>)}</select>{secondaryOptions.length>0&&<select value={secondary} onChange={e=>setSecondary(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm" aria-label={type==="people"?"Filter by skill":"Filter by role"}><option>All</option>{secondaryOptions.map(x=><option key={x}>{x}</option>)}</select>}{type==="people"&&<><select value={interest} onChange={e=>setInterest(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm" aria-label="Filter by interest"><option>All</option>{[...new Set(students.flatMap(x=>x.interests))].map(x=><option key={x}>{x}</option>)}</select><select value={collaboration} onChange={e=>setCollaboration(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm" aria-label="Filter by collaboration"><option>All</option><option>Open to projects</option><option>Open to mentoring</option><option>Focused</option></select></>}{type==="events"&&<div className="flex rounded-md border p-0.5"><Button size="sm" variant={view==="list"?"secondary":"ghost"} onClick={()=>setView("list")}><List className="size-4"/>List</Button><Button size="sm" variant={view==="calendar"?"secondary":"ghost"} onClick={()=>setView("calendar")}><CalendarDays className="size-4"/>Calendar</Button></div>}<span className="lg:ms-auto text-xs text-muted-foreground">{filtered.length} results</span></div>
  {filtered.length?<DirectoryResults type={type} items={filtered} view={view}/>:<div className="surface rounded-lg py-20 text-center"><Search className="mx-auto size-5 text-muted-foreground"/><h2 className="mt-4 font-semibold">Nothing matched “{query}”</h2><p className="mt-1 text-sm text-muted-foreground">Try broader filters or a different topic.</p><Button className="mt-5" variant="outline" onClick={()=>{setQuery("");setPrimary("All");setSecondary("All");setInterest("All");setCollaboration("All")}}>Clear filters</Button></div>}</>;
}

function DirectoryResults({type,items,view}:{type:DirectoryType;items:Array<Student|Community|Project|CampusEvent>;view:"list"|"calendar"}){if(type==="people")return <div className="grid gap-x-10 lg:grid-cols-2">{(items as Student[]).map(s=><StudentCard key={s.username} student={s}/>)}</div>;if(type==="communities")return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{(items as Community[]).map(c=><CommunityCard key={c.slug} community={c}/>)}</div>;if(type==="projects")return <div className="surface rounded-lg p-5 sm:p-7">{(items as Project[]).map(p=><ProjectRow key={p.slug} project={p}/>)}</div>;if(view==="calendar")return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(items as CampusEvent[]).map(e=><div key={e.slug} className="surface rounded-lg p-4"><p className="eyebrow">{e.month} {e.day}</p><EventRow event={e}/></div>)}</div>;return <div className="surface rounded-lg p-5 sm:p-7">{(items as CampusEvent[]).map(e=><EventRow key={e.slug} event={e}/>)}</div>}
