"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarPlus, FolderPlus, Plus, Send } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { communities } from "@/lib/data/mock";
import { slugify, useDemoState } from "@/lib/demo/demo-store";

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label>}

export function PostDialog({variant="outline"}:{variant?:"outline"|"default"}){
  const [open,setOpen]=useState(false);const {createPost,state}=useDemoState();
  function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const text=String(data.get("text")??"").trim();if(text.length<4){toast.error("Write at least a few words.");return;}const tags=String(data.get("tags")??"").split(",").map(x=>x.trim()).filter(Boolean).slice(0,4);createPost({id:`post-${Date.now()}`,authorUsername:state.profile.username,context:String(data.get("community")||"QAIRU campus"),communitySlug:String(data.get("communitySlug")||"")||undefined,createdAt:"Just now",text,tags,likes:0});toast.success("Post published to the campus feed");setOpen(false);}
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant={variant}><Plus className="size-4"/>Post</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Share with QAIRU</DialogTitle><DialogDescription>Post an update, question or early idea to the founding student community.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><Field label="Post"><Textarea name="text" autoFocus placeholder="What are you building, learning or looking for?" className="min-h-32"/></Field><Field label="Community (optional)"><select name="community" className="h-10 rounded-md border bg-background px-3 text-sm"><option value="QAIRU campus">QAIRU campus</option>{communities.map(c=><option key={c.slug} value={c.name}>{c.name}</option>)}</select></Field><Field label="Tags (optional, comma-separated)"><Input name="tags" placeholder="AI, first prototype"/></Field><DialogFooter><Button type="submit"><Send className="size-4"/>Publish post</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function ProjectDialog({compact=false}:{compact?:boolean}){
  const [open,setOpen]=useState(false);const {createProject,state}=useDemoState();const router=useRouter();
  function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const name=String(data.get("name")??"").trim();const description=String(data.get("description")??"").trim();if(name.length<3||description.length<10){toast.error("Add a project name and a clearer description.");return;}const slug=slugify(name);createProject({slug,name,tagline:String(data.get("tagline")||description.slice(0,80)),description,status:"Idea",category:String(data.get("category")||"Student initiative"),technologies:String(data.get("technologies")||"").split(",").map(x=>x.trim()).filter(Boolean),lookingFor:String(data.get("roles")||"").split(",").map(x=>x.trim()).filter(Boolean),creator:state.profile.name,members:["AS"]});toast.success("Project published");setOpen(false);router.push(`/projects/${slug}`);}
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size={compact?"sm":"default"}><FolderPlus className="size-4"/>{compact?"New project":"Publish project"}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Publish a project</DialogTitle><DialogDescription>Start with an honest early-stage brief. You can recruit collaborators immediately.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="Project name"><Input name="name" required/></Field><Field label="One-line promise"><Input name="tagline" required placeholder="What changes if this works?"/></Field><Field label="Description"><Textarea name="description" required className="min-h-24"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Category"><Input name="category" placeholder="Campus, EdTech…"/></Field><Field label="Technologies"><Input name="technologies" placeholder="Next.js, Python"/></Field></div><Field label="Roles you need"><Input name="roles" placeholder="Designer, researcher"/></Field><DialogFooter><Button type="submit">Publish project</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function CommunityDialog(){const [open,setOpen]=useState(false);const {createCommunity}=useDemoState();
  function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const name=String(data.get("name")??"").trim();const description=String(data.get("description")??"").trim();if(name.length<3||description.length<8){toast.error("Add a name and short description.");return;}createCommunity({slug:slugify(name),name,category:String(data.get("category")||"Student-led"),description,purpose:String(data.get("purpose")||""),members:1,accent:"#5b6fd8",status:"Forming"});toast.success("Community started in Forming status");setOpen(false);}
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="size-4"/>Start a community</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Start a community</DialogTitle><DialogDescription>New groups begin as Forming while founding members gather.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="Name"><Input name="name" required/></Field><Field label="Category"><Input name="category" required placeholder="Technology, Culture…"/></Field><Field label="Short description"><Textarea name="description" required/></Field><Field label="Purpose"><Textarea name="purpose" placeholder="Why should this group exist at QAIRU?"/></Field><DialogFooter><Button type="submit">Start community</Button></DialogFooter></form></DialogContent></Dialog>}

export function EventDialog({dark=false}:{dark?:boolean}){const [open,setOpen]=useState(false);const {createEvent}=useDemoState();
 function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const title=String(data.get("title")??"").trim();const dateValue=String(data.get("date")??"");if(title.length<3||!dateValue){toast.error("Add a title and date.");return;}const date=new Date(`${dateValue}T12:00:00`);createEvent({slug:slugify(title),title,description:String(data.get("description")||"A student-led QAIRU event."),date:date.toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"}),day:String(date.getDate()).padStart(2,"0"),month:date.toLocaleDateString("en-US",{month:"short"}).toUpperCase(),time:String(data.get("time")||"18:00"),location:String(data.get("location")||"QAIRU campus"),category:String(data.get("category")||"Community event"),organizer:"Aruzhan Sarsembayeva",attendees:1,capacity:Number(data.get("capacity"))||30});toast.success("Event added to the campus calendar");setOpen(false);}
 return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant={dark?"secondary":"default"}><CalendarPlus className="size-4"/>Create event</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create an event</DialogTitle><DialogDescription>Publish a clear plan for QAIRU’s first student cohort.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="Title"><Input name="title" required/></Field><Field label="Description"><Textarea name="description" required/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Date"><Input name="date" type="date" required/></Field><Field label="Time"><Input name="time" placeholder="18:00–20:00" required/></Field><Field label="Location"><Input name="location" required/></Field><Field label="Capacity"><Input name="capacity" type="number" min="2" defaultValue="30"/></Field></div><Field label="Category"><Input name="category" placeholder="Workshop"/></Field><DialogFooter><Button type="submit">Create event</Button></DialogFooter></form></DialogContent></Dialog>}

export function ResourceDialog(){const [open,setOpen]=useState(false);const {createResource,state}=useDemoState();function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const title=String(data.get("title")??"").trim();const description=String(data.get("description")??"").trim();if(title.length<3||description.length<8){toast.error("Add a title and useful description.");return;}createResource({id:slugify(title),title,description,category:String(data.get("category")||"General"),type:String(data.get("type")||"Guide"),author:state.profile.name,authorUsername:state.profile.username,tags:String(data.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean),saves:0});toast.success("Resource shared");setOpen(false);}return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="size-4"/>Share resource</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Share a resource</DialogTitle><DialogDescription>Add context so students know why this is useful. Demo resources open in an internal detail view.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="Title"><Input name="title" required/></Field><Field label="Description"><Textarea name="description" required/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Category"><Input name="category"/></Field><Field label="Type"><Input name="type" placeholder="Guide, Notes…"/></Field></div><Field label="Tags"><Input name="tags" placeholder="Research, Template"/></Field><DialogFooter><Button type="submit">Share resource</Button></DialogFooter></form></DialogContent></Dialog>}
