"use client";

import { ClientNavLink } from "@/components/shared/client-nav-link";
import { CalendarDays, Clock, Code2, MapPin, Share2, Users } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { AvatarMark } from "@/components/shared/avatar-mark";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { communities, events, projects, resources, students } from "@/lib/data/mock";
import { shareDemo } from "@/lib/demo/share";
import { useDemoState } from "@/lib/demo/demo-store";

export function ProjectDetail({slug}:{slug:string}) {
  const {state,toggleIn,applyToProject}=useDemoState();
  const [open,setOpen]=useState(false);
  const project=[...state.createdProjects,...projects].find(item=>item.slug===slug);
  if(!project)return <Missing/>;
  const saved=state.savedProjectSlugs.includes(slug);const applied=state.projectApplications[slug];
  function apply(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const role=String(data.get("role")||"");const message=String(data.get("message")||"").trim();if(!role||message.length<5){toast.error("Choose a role and add a short message.");return;}applyToProject(slug,role,message);setOpen(false);toast.success("Application sent to the project team");}
  return <div className="page-container">
    <header className="border-b pb-8"><div className="flex items-center gap-2"><Badge>{project.status}</Badge><span className="text-xs text-muted-foreground">{project.category}</span></div><div className="mt-5 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-balance text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">{project.name}</h1><p className="mt-3 max-w-2xl text-lg text-muted-foreground">{project.tagline}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>toggleIn("savedProjectSlugs",slug)}>{saved?"Saved":"Save"}</Button><Button variant="outline" size="icon" onClick={()=>shareDemo(project.name,`/projects/${slug}`)} aria-label="Share project"><Share2 className="size-4"/></Button><Button onClick={()=>setOpen(true)} disabled={!!applied}>{applied?"Application sent":"Apply to join"}</Button></div></div></header>
    <div className="grid gap-10 py-8 xl:grid-cols-[1fr_300px]"><div><p className="eyebrow">About the project</p><p className="mt-4 max-w-3xl text-base leading-7">{project.description}</p><section className="mt-10"><p className="eyebrow">Open roles</p><div className="mt-4 divide-y rounded-lg border">{project.lookingFor.length?project.lookingFor.map(role=><Button key={role} variant="ghost" onClick={()=>setOpen(true)} className="h-auto w-full justify-between rounded-none p-4"><span className="text-sm font-semibold">{role}</span><span className="text-xs">Apply →</span></Button>):<p className="p-5 text-sm text-muted-foreground">The team is complete. Save it for future openings.</p>}</div></section><section className="mt-10 border-s ps-5"><p className="eyebrow">Build log · August 12</p><p className="mt-2 text-sm font-medium">The first working concept is ready for feedback</p><p className="mt-2 text-sm text-muted-foreground">Decisions are documented so new contributors can join without losing context.</p></section></div><aside className="space-y-6"><section className="surface rounded-lg p-5"><p className="eyebrow">Team</p><div className="mt-5 flex -space-x-2">{project.members.map((initials,index)=><AvatarMark key={initials} initials={initials} color={["#5b6fd8","#85629a","#b15e59"][index%3]} className="size-10 border-2 border-card"/>)}</div><p className="mt-4 text-xs text-muted-foreground">{project.members.length} contributors · {project.creator}</p></section><div className="flex flex-wrap gap-2">{project.technologies.map(item=><Badge key={item} variant="secondary">{item}</Badge>)}</div><Button variant="outline" className="w-full" onClick={()=>toast.info("Repository link will appear when the team connects one.")}><Code2 className="size-4"/>Repository not connected</Button></aside></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Apply to {project.name}</DialogTitle><DialogDescription>Tell the founding team where you can contribute.</DialogDescription></DialogHeader><form onSubmit={apply} className="grid gap-4"><label className="grid gap-2 text-sm font-medium">Role<select name="role" className="h-10 rounded-md border bg-background px-3"><option value="">Choose a role</option>{project.lookingFor.map(role=><option key={role}>{role}</option>)}<option>General contributor</option></select></label><label className="grid gap-2 text-sm font-medium">Message<Textarea name="message" placeholder="I can help because…"/></label><DialogFooter><Button type="submit">Send application</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}

export function EventDetail({slug}:{slug:string}) {
  const {state,toggleIn}=useDemoState();const event=[...state.createdEvents,...events].find(item=>item.slug===slug);if(!event)return <Missing/>;const attending=state.attendingEventSlugs.includes(slug);const saved=state.savedEventSlugs.includes(slug);const count=event.attendees+(attending?1:0);
  return <div className="page-container"><div className="grid gap-10 xl:grid-cols-[1fr_320px]"><div><header className="border-b pb-8"><Badge variant="secondary">{event.category}</Badge><h1 className="mt-5 text-balance text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">{event.title}</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-muted-foreground">{event.description}</p><p className="mt-6 text-sm">Organized by <strong>{event.organizer}</strong></p></header><section className="py-8"><p className="eyebrow">About this event</p><p className="mt-4 max-w-2xl text-sm leading-7">Meet the founding cohort, exchange practical feedback and leave with a clear next step.</p><h2 className="mt-10 text-xl font-semibold">Who’s going</h2><div className="mt-4 flex items-center"><div className="flex -space-x-2">{students.slice(0,8).map(student=><AvatarMark key={student.username} initials={student.initials} color={student.color} className="size-9 border-2 border-background"/>)}</div><p className="ms-4 text-xs text-muted-foreground">{count} / {event.capacity} attending</p></div></section></div><aside><div className="surface rounded-lg p-5"><div className="space-y-5"><Info icon={CalendarDays} label="Date" value={event.date}/><Info icon={Clock} label="Time" value={event.time}/><Info icon={MapPin} label="Location" value={event.location}/><Info icon={Users} label="Capacity" value={`${count} / ${event.capacity} attending`}/></div><div className="mt-6 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${Math.min(100,Math.round(count/event.capacity*100))}%`}}/></div><Button className="mt-6 w-full" variant={attending?"outline":"default"} onClick={()=>toggleIn("attendingEventSlugs",slug)}>{attending?"You’re attending":"Attend event"}</Button><div className="mt-2 grid grid-cols-2 gap-2"><Button variant="outline" onClick={()=>toggleIn("savedEventSlugs",slug)}>{saved?"Saved":"Save"}</Button><Button variant="outline" onClick={()=>shareDemo(event.title,`/events/${slug}`)}><Share2 className="size-4"/>Share</Button></div></div></aside></div></div>;
}

export function CommunityDetail({slug}:{slug:string}) {
  const {state,toggleIn}=useDemoState();const community=[...state.createdCommunities,...communities].find(item=>item.slug===slug);if(!community)return <Missing/>;const joined=state.joinedCommunitySlugs.includes(slug);const count=community.members+(joined?1:0);
  return <div><div className="h-44 sm:h-56" style={{background:`linear-gradient(135deg,${community.accent},#111827)`}}/><div className="page-container -mt-12"><header className="surface relative rounded-lg p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end"><div className="grid size-20 place-items-center rounded-lg border-4 border-card text-2xl font-semibold text-white" style={{backgroundColor:community.accent}}>{community.name.split(" ").map(item=>item[0]).slice(0,2).join("")}</div><div className="flex-1"><div className="flex items-center gap-2"><p className="eyebrow">{community.category} community</p><Badge variant="secondary">{community.status??"Active"}</Badge></div><h1 className="mt-1 text-3xl font-semibold">{community.name}</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">{community.description}</p></div><Button variant={joined?"outline":"default"} onClick={()=>toggleIn("joinedCommunitySlugs",slug)}>{joined?"Leave":"Join"}</Button></div><p className="mt-6 border-t pt-4 text-xs text-muted-foreground">{count} members · Student-led</p></header><Tabs defaultValue="posts" className="mt-8"><TabsList><TabsTrigger value="posts">Posts</TabsTrigger><TabsTrigger value="members">Members</TabsTrigger><TabsTrigger value="events">Events</TabsTrigger><TabsTrigger value="resources">Resources</TabsTrigger></TabsList><TabsContent value="posts" className="surface mt-4 divide-y rounded-lg">{students.slice(0,3).map((student,index)=><article key={student.username} className="p-5"><ClientNavLink href={`/u/${student.username}`} className="flex w-fit gap-3"><AvatarMark initials={student.initials} color={student.color} className="size-8"/><p className="text-xs font-semibold">{student.name}</p></ClientNavLink><p className="mt-4 text-sm">{["Sharing notes from our first session and the next topics we’ll explore.","We need two volunteers for the upcoming open session.","Our founding resource list is now live."][index]}</p></article>)}</TabsContent><TabsContent value="members" className="mt-4 grid gap-3 sm:grid-cols-2">{students.slice(0,8).map(student=><ClientNavLink key={student.username} href={`/u/${student.username}`} className="surface flex items-center gap-3 rounded-lg p-4"><AvatarMark initials={student.initials} color={student.color} className="size-9"/><span className="text-sm font-medium">{student.name}</span></ClientNavLink>)}</TabsContent><TabsContent value="events" className="mt-4 space-y-3">{events.slice(0,3).map(event=><ClientNavLink key={event.slug} href={`/events/${event.slug}`} className="surface block rounded-lg p-4">{event.title}</ClientNavLink>)}</TabsContent><TabsContent value="resources" className="mt-4 space-y-3">{resources.slice(0,4).map(resource=><ClientNavLink key={resource.id} href={`/resources?resource=${resource.id}`} className="surface block rounded-lg p-4">{resource.title}</ClientNavLink>)}</TabsContent></Tabs></div></div>;
}

function Missing(){return <div className="page-container py-24 text-center"><h1 className="text-2xl font-semibold">This demo item was not found</h1><Button asChild className="mt-5"><ClientNavLink href="/home">Back to Home</ClientNavLink></Button></div>}
function Info({icon:Icon,label,value}:{icon:typeof Clock;label:string;value:string}){return <div className="flex gap-3"><span className="grid size-9 place-items-center rounded-md bg-muted"><Icon className="size-4"/></span><div><p className="text-[10px] uppercase text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div></div>}
