"use client";

import Link from "next/link";
import { ArrowRight, Bookmark, Heart, MessageCircle, Share2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { AvatarMark } from "@/components/shared/avatar-mark";
import { PostDialog, ProjectDialog, EventDialog } from "@/components/demo/create-dialogs";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { communities, events, opportunities, projects, students } from "@/lib/data/mock";
import { demoPosts, useDemoState } from "@/lib/demo/demo-store";
import { cn } from "@/lib/utils";
import { isLiveMode } from "@/lib/app-mode";
import { useCurrentUser } from "@/lib/auth/current-user-provider";
import type { DemoPost } from "@/types";

export function HomeFeed(){const {state}=useDemoState();const allPosts=[...state.createdPosts,...demoPosts];const current=students.find(x=>x.username==="aruzhan")!;return <div className="page-container"><div className="grid gap-10 xl:grid-cols-[minmax(0,1fr)_310px]"><div>
 <section className="border-b pb-8"><p className="eyebrow">Thursday · August 13</p><div className="mt-2 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold tracking-[-0.045em] sm:text-4xl">Good afternoon, <GreetingName/>.</h1><p className="mt-2 text-sm text-muted-foreground">Here’s what the founding QAIRU cohort is moving today.</p></div><div className="flex gap-2"><PostDialog/><ProjectDialog compact/></div></div></section>
 <section className="py-8"><div className="grid overflow-hidden rounded-lg border bg-border sm:grid-cols-3 sm:gap-px"><TodayItem label="Next event" title={events[0].title} meta={`${events[0].time} · ${events[0].location}`} href={`/events/${events[0].slug}`} tone/><TodayItem label="Project match" title={projects[1].name} meta="Needs a GIS contributor" href={`/projects/${projects[1].slug}`}/><TodayItem label="New opportunity" title={opportunities[0].title} meta={`Apply by ${opportunities[0].deadline}`} href="/opportunities?opportunity=yandex-ml"/></div></section>
 <section><div className="mb-4 flex items-center justify-between"><div><p className="eyebrow">Your campus</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.03em]">Recent activity</h2></div><span className="text-xs text-muted-foreground">{allPosts.length} updates</span></div><div className="surface divide-y rounded-lg">{allPosts.map(post=><Post key={post.id} post={post} current={current}/>)}</div></section>
 </div><aside className="space-y-8"><section><div className="mb-3 flex items-center justify-between"><p className="eyebrow">Upcoming</p><Link href="/events" className="text-xs text-muted-foreground hover:text-foreground">Calendar →</Link></div><div className="surface rounded-lg p-4">{events.slice(0,3).map(e=><Link key={e.slug} href={`/events/${e.slug}`} className="flex gap-3 border-b py-3 first:pt-0 last:border-0 last:pb-0"><div className="w-9 text-center"><p className="text-[9px] font-semibold text-primary">{e.month}</p><p className="font-mono text-base font-semibold">{e.day}</p></div><div><p className="text-xs font-medium leading-5">{e.title}</p><p className="text-[11px] text-muted-foreground">{e.time}</p></div></Link>)}</div></section>
  <section><div className="mb-3 flex items-center justify-between"><p className="eyebrow">Founding communities</p><Link href="/communities" className="text-xs text-muted-foreground hover:text-foreground">Explore →</Link></div><div className="space-y-2">{communities.slice(0,3).map(c=><Link href={`/communities/${c.slug}`} key={c.slug} className="surface flex items-center gap-3 rounded-lg p-3 transition-colors hover:bg-accent"><span className="size-2 rounded-full" style={{backgroundColor:c.accent}}/><div className="min-w-0"><p className="truncate text-xs font-medium">{c.name}</p><p className="text-[11px] text-muted-foreground">{c.members} members · {c.status}</p></div><ArrowRight className="ms-auto size-3.5 text-muted-foreground"/></Link>)}</div></section>
  <section className="rounded-lg bg-foreground p-5 text-background"><p className="text-[10px] uppercase tracking-[.15em] opacity-55">Quick action</p><h3 className="mt-4 font-semibold">Start a campus moment</h3><p className="mt-2 text-xs leading-5 opacity-65">Create one of the events that QAIRU’s first students will remember.</p><div className="mt-5"><EventDialog dark/></div></section>
 </aside></div></div>}

function GreetingName(){return isLiveMode?<LiveGreetingName/>:<DemoGreetingName/>}
function LiveGreetingName(){const{profile}=useCurrentUser();return <>{profile.fullName.split(" ")[0]}</>}
function DemoGreetingName(){const{state}=useDemoState();return <>{state.profile.name.split(" ")[0]}</>}

function TodayItem({label,title,meta,href,tone}:{label:string;title:string;meta:string;href:string;tone?:boolean}){return <Link href={href} className={`group p-5 ${tone?"bg-primary text-primary-foreground":"bg-card"}`}><p className={`text-[10px] font-semibold uppercase tracking-[.13em] ${tone?"opacity-65":"text-muted-foreground"}`}>{label}</p><p className="mt-5 text-sm font-semibold">{title}</p><p className={`mt-1 text-xs ${tone?"opacity-70":"text-muted-foreground"}`}>{meta}</p><ArrowRight className="mt-5 size-4 transition-transform group-hover:translate-x-1"/></Link>}

function Post({post,current}:{post:DemoPost;current:(typeof students)[number]}){const {state,toggleIn,addComment}=useDemoState();const [commentsOpen,setCommentsOpen]=useState(false);const author=post.authorUsername===state.profile.username?{...current,name:state.profile.name,username:state.profile.username}:students.find(x=>x.username===post.authorUsername)??current;const liked=state.likedPostIds.includes(post.id);const saved=state.bookmarkedPostIds.includes(post.id);const comments=state.comments[post.id]??[];async function share(){const url=`${location.origin}/home?post=${post.id}`;try{if(navigator.share)await navigator.share({title:"QAIRU Hub post",text:post.text,url});else{await navigator.clipboard.writeText(url);toast.success("Post link copied");}}catch{}}
 function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const input=event.currentTarget.elements.namedItem("comment") as HTMLInputElement;const text=input.value.trim();if(!text){toast.error("Write a comment first.");return;}addComment(post.id,text);input.value="";toast.success("Comment added");}
 return <article id={post.id} className="p-5 sm:p-6"><Link href={`/u/${author.username}`} className="flex w-fit items-start gap-3"><AvatarMark initials={author.initials} color={author.color} className="size-9"/><div><p className="text-sm font-semibold hover:text-primary">{author.name}</p><p className="text-[11px] text-muted-foreground">{post.context} · {post.createdAt}</p></div></Link><p className="mt-4 max-w-2xl text-sm leading-6">{post.text}</p><div className="mt-3 flex flex-wrap gap-1.5">{post.tags.map(t=><Badge key={t} variant="secondary" className="font-normal">{t}</Badge>)}</div><div className="mt-5 flex items-center gap-1 border-t pt-3"><Button size="sm" variant="ghost" onClick={()=>toggleIn("likedPostIds",post.id)} aria-pressed={liked}><Heart className={cn("size-4",liked&&"fill-primary text-primary")}/>{post.likes+(liked?1:0)}</Button><Button size="sm" variant="ghost" onClick={()=>setCommentsOpen(true)}><MessageCircle className="size-4"/>{comments.length}</Button><Button size="icon-sm" variant="ghost" onClick={share} aria-label="Share post"><Share2 className="size-4"/></Button><Button className="ms-auto" size="icon-sm" variant="ghost" onClick={()=>{toggleIn("bookmarkedPostIds",post.id);toast.success(saved?"Bookmark removed":"Post bookmarked")}} aria-label="Bookmark post" aria-pressed={saved}><Bookmark className={cn("size-4",saved&&"fill-current text-primary")}/></Button></div><Dialog open={commentsOpen} onOpenChange={setCommentsOpen}><DialogContent><DialogHeader><DialogTitle>Post discussion</DialogTitle><DialogDescription>{comments.length?`${comments.length} comment${comments.length===1?"":"s"}`:"Start the conversation"}</DialogDescription></DialogHeader><div className="max-h-72 space-y-3 overflow-y-auto">{comments.map(c=><div key={c.id} className="rounded-lg bg-muted p-3"><p className="text-xs font-semibold">{c.authorUsername===state.profile.username?state.profile.name:c.authorUsername}</p><p className="mt-1 text-sm">{c.text}</p><p className="mt-1 text-[10px] text-muted-foreground">{c.createdAt}</p></div>)}{!comments.length&&<p className="py-8 text-center text-sm text-muted-foreground">No comments yet.</p>}</div><form onSubmit={submit} className="flex gap-2"><Input name="comment" placeholder="Add a constructive comment…" autoComplete="off"/><DialogFooter><Button type="submit">Comment</Button></DialogFooter></form></DialogContent></Dialog></article>}
