import Link from "next/link";
import { ArrowRight, CalendarDays, FolderKanban, Sparkles } from "lucide-react";
import { LiveEventDialog, LiveProjectDialog } from "@/components/social/live-create-dialogs";
import { Badge } from "@/components/ui/badge";
import type { LiveCommunity, LiveEvent, LiveProject } from "@/lib/data/social";

export function LiveHome({ firstName, communities, projects, events }: { firstName: string; communities: LiveCommunity[]; projects: LiveProject[]; events: LiveEvent[] }) {
  const upcoming = events.filter((event) => new Date(event.endsAt) >= new Date()).slice(0, 4);
  return <div className="page-container"><div className="grid gap-10 xl:grid-cols-[1fr_290px]">
    <div>
      <section className="border-b pb-8"><p className="eyebrow">Live campus</p><div className="mt-2 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold tracking-[-0.045em] sm:text-4xl">Welcome back, {firstName}.</h1><p className="mt-2 text-sm text-muted-foreground">Everything below comes from your QAIRU Hub database.</p></div><LiveProjectDialog compact /></div></section>
      <section className="py-8"><div className="grid overflow-hidden rounded-lg border bg-border sm:grid-cols-3 sm:gap-px"><Metric label="Communities" value={communities.length} href="/communities" icon={Sparkles} /><Metric label="Projects" value={projects.length} href="/projects" icon={FolderKanban} /><Metric label="Upcoming events" value={upcoming.length} href="/events" icon={CalendarDays} /></div></section>
      <section><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Build together</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.03em]">Latest projects</h2></div><Link href="/projects" className="text-xs text-muted-foreground hover:text-foreground">View all →</Link></div>{projects.length ? <div className="surface divide-y rounded-lg">{projects.slice(0, 5).map((project) => <Link key={project.id} href={`/projects/${project.slug}`} className="group flex items-center gap-4 p-5"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-semibold group-hover:text-primary">{project.name}</h3><Badge variant="secondary" className="capitalize">{project.status}</Badge></div><p className="mt-1 truncate text-xs text-muted-foreground">{project.tagline}</p></div><span className="hidden text-xs text-muted-foreground sm:block">{project.memberCount} team members</span><ArrowRight className="size-4 text-muted-foreground" /></Link>)}</div> : <div className="surface rounded-lg border-dashed p-10 text-center"><h3 className="font-semibold">No live projects yet</h3><p className="mt-2 text-sm text-muted-foreground">Publish the first brief and recruit collaborators.</p><div className="mt-5"><LiveProjectDialog compact /></div></div>}</section>
      <section className="mt-10 border-t pt-8"><p className="eyebrow">Campus activity</p><h2 className="mt-1 text-xl font-semibold">Posts are still demo-only</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">The live feed is intentionally empty in Phase 2B-1. No fictional posts are mixed into your real account.</p></section>
    </div>
    <aside className="space-y-8">
      <section><div className="mb-3 flex items-center justify-between"><p className="eyebrow">Upcoming</p><Link href="/events" className="text-xs text-muted-foreground hover:text-foreground">Calendar →</Link></div>{upcoming.length ? <div className="surface rounded-lg p-4">{upcoming.map((event) => { const date = new Date(event.startsAt); return <Link key={event.id} href={`/events/${event.slug}`} className="flex gap-3 border-b py-3 first:pt-0 last:border-0 last:pb-0"><div className="w-9 text-center"><p className="text-[9px] font-semibold text-primary">{date.toLocaleDateString("en", { month: "short" }).toUpperCase()}</p><p className="font-mono text-base font-semibold">{date.getDate()}</p></div><div className="min-w-0"><p className="truncate text-xs font-medium leading-5">{event.title}</p><p className="text-[11px] text-muted-foreground">{date.toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit" })}</p></div></Link>; })}</div> : <div className="rounded-lg border border-dashed p-6 text-center text-xs text-muted-foreground">No upcoming events.</div>}</section>
      <section><div className="mb-3 flex items-center justify-between"><p className="eyebrow">Communities</p><Link href="/communities" className="text-xs text-muted-foreground hover:text-foreground">Explore →</Link></div>{communities.length ? <div className="space-y-2">{communities.slice(0, 4).map((community) => <Link href={`/communities/${community.slug}`} key={community.id} className="surface flex items-center gap-3 rounded-lg p-3 transition-colors hover:bg-accent"><span className="size-2 rounded-full bg-primary" /><div className="min-w-0"><p className="truncate text-xs font-medium">{community.name}</p><p className="text-[11px] text-muted-foreground">{community.memberCount} members · {community.status}</p></div><ArrowRight className="ms-auto size-3.5 text-muted-foreground" /></Link>)}</div> : <p className="rounded-lg border border-dashed p-5 text-center text-xs text-muted-foreground">No live communities yet.</p>}</section>
      <section className="rounded-lg bg-foreground p-5 text-background"><p className="text-[10px] uppercase tracking-[.15em] opacity-55">Quick action</p><h3 className="mt-4 font-semibold">Start a campus moment</h3><p className="mt-2 text-xs leading-5 opacity-65">Create a real event with database-enforced capacity.</p><div className="mt-5"><LiveEventDialog dark /></div></section>
    </aside>
  </div></div>;
}

function Metric({ label, value, href, icon: Icon }: { label: string; value: number; href: string; icon: typeof Sparkles }) {
  return <Link href={href} className="group bg-card p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-muted-foreground">{label}</p><Icon className="size-4 text-muted-foreground" /></div><p className="mt-5 text-3xl font-semibold tracking-[-0.04em]">{value}</p><p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground">Explore <ArrowRight className="size-3 transition-transform group-hover:translate-x-1" /></p></Link>;
}
